name: Monthly build
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD-HHmm'
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.time.outputs.time }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          prerelease: true
    outputs:
      release_id: ${{ steps.release.outputs.id }}
  build:
    runs-on: ubuntu-latest
    needs: prepare_release
    strategy:
      matrix:
        boards: [rock-5b]
        build_systems: [rbuild, armbian]
        distros: [debian, ubuntu]
        flavors: [kde, cli]
        exclude:
          - build_systems: debos
            distros: debian
            flavors: cli
          - build_systems: debos
            distros: ubuntu
            flavors: kde
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Armbian image
        uses: radxa/armbian-compile-action@main
        if: matrix.build_systems == 'armbian'
        with:
          board: ${{ matrix.boards }}
          distro: ${{ matrix.distros }}
          flavor: ${{ matrix.flavors }}
          kernel_branch: legacy
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload debos-radxa image
        uses: radxa/debos-build-action@main
        if: matrix.build_systems == 'debos'
        with:
          board: ${{ matrix.boards }}
          distro: ${{ matrix.distros }}
          flavor: ${{ matrix.flavors }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload rbuild image
        uses: radxa-repo/rbuild@main
        if: matrix.build_systems == 'rbuild'
        with:
          board: ${{ matrix.boards }}
          distro: ${{ matrix.distros }}
          flavor: ${{ matrix.flavors }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
